name: Daily Backend Activity

on:
  schedule:
    - cron: "30 4 * * *"   # Runs daily at 10:00 AM IST
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update daily log
        run: |
          echo "Last update: $(date)" >> daily_log.txt

      - name: Commit and push
        run: |
          git config user.name "Aditya Jannawar"
          git config user.email "adityajannawar249@gmail.com"
          git add daily_log.txt
          git commit -m "chore: daily backend activity update" || echo "No changes"
          git push
